### PR TITLE
Pigeon CLI

### PR DESCRIPTION
**Pull request by rathrio**
`./pigeon start` starts the bot.

### CODE REVIEW

**Comment by simplay** [comment]
@rathrio: is this PR ready for being merged?

**Comment by rathrio** [comment]
@simplay in a sec

**Comment by rathrio** [comment]
@simplay ok merged master. would you mind running `./pigeon start` on this branch to check whether it starts up correctly?

**Comment by rathrio** [comment]
@simplay oh and you need to `bundle` first

**Comment by simplay** [comment]
@rathrio: Exit kills jruby's threads (exits them). Thus, remove the exit statement (otherwise the task **start** establishes a connection and then shuts down soon afer. With my changes, the process seems to start and keeps running.

**Comment by rathrio** [comment]
@simplay ok, nice. thanks.

**Comment by rathrio** [comment]
I propose we merge this then and implement process handling with something like [godrb](http://godrb.com/) later on.

**Comment by simplay** [comment]
agree :+1:

**Pull request merged**
