### PR TITLE
Peparing proper test setup

### PR DESCRIPTION
**Pull request by simplay**
running a test ts3 server allowing for establishing real-connections
hosted by a local server during runtime.

offers a real test scenario.

### CODE REVIEW

**Comment by simplay** [comment]
@rathrio: yes, without changing the directory within the thread's scope, my ts3 test server was not able to load its db. have you verified this change (i.e. does rake still run)? i'm gonna check this soon. Apart from this little change, is there anything missing/should be added or is this PR ready for being merged?

**Comment by rathrio** [comment]
@simplay Ok I'll check the path stuff out again and merge it. This is awesome! On some runs the bot failed to authenticate though.

**Comment by simplay** [comment]
@rathrio: It is possible that the server has a very slow start up. Then, the bot tries to connect even though the server has not been started properly yet. This is why I added the `sleep 3` statement. Maybe we just should increase the sleep time a little (from 3 secs up to 5). However, the final goal would be to have some kind of _server is ready check_ and only then, when succeeded, run the tests.

**Comment by rathrio** [comment]
@simplay ok I'll run it with more :zzz: time.

Maybe the server just generated different credentials on my machine the first time I ran the tests. Could that be possible?

**Comment by simplay** [comment]
Not sure whether this is the case. I was assuming that all relevant server data was pushed onto the repo. Shouldn't then the test server - that is run on my and your machine (or any machine), be using the same credentials?

**Comment by rathrio** [comment]
@simplay yes, you're right. I tried a couple of different sleep times. At 8 seconds it seemed to work.

But look at that motherfucker now:

```
< error id=3329 msg=connection\sfailed,\syou\sare\sbanned extra_msg=you\smay\sretry\sin\s542\sseconds
```

haha

**Comment by simplay** [comment]
@rathrio: We probably shouldn't ban the user "Query Sever Admin" (the bot), after committing several connection attempts. ^^'
This can be specified in the server config. I'm gonna reconfigure this right away. XD

**Comment by rathrio** [comment]
@simplay I approve :smile:

**Comment by rathrio** [comment]
@simplay now I always get

```
[login] < error id=520 msg=invalid\sloginname\sor\spassword
```

no matter how long I sleep. Any suggestions?

**Comment by simplay** [comment]
hmm, maybe, depsit sharing the db, your server uses different login information than mine. :S

**Comment by rathrio** [comment]
Ok, proposition time:

How about the server the we download into `test/servers` is the server we use to test locally as well? So it's not just the test server, but also the development server. This way we don't have to care about separate credentials and assume that `ENV` will always provide us with the correct ones.

I have implemented a version where the test credentials are stores in a yaml file but it seems so redundant. What do you think?

**Comment by simplay** [comment]
idea1: the test server should only be used for testing purposes. The production server should be independent from pigeon. Pigeon should only be an add-on to a server (even though it requires a server's credentials). 
idea2: Pigeon should not only be a bot, but a whole server plus add-ons. 

The initial idea was idea#1. Furthermore, a pigeon should be able to connect to foreign servers (at some point). therefore i am not sure whether solution 2 makes sense. But i agree, including the whole server thingy twice is way too redundant. i introduced a new ENV variable, called p_server_path, pointing to the server script.

**Comment by rathrio** [comment]
@simplay I like idea1 much much better. The server is only bundled for dev and testing purposes, but a production pigeon may infect any server :smile:. 

I can't think of an optimal solution...

**Comment by simplay** [comment]
@rathrio: I'm gonna merge this PR for bravery's sake. Sure, this is still not the optimal solution, but I think, eventually, we will find a strategy how we want to deal with all mentioned issues in this PR. For now, I guess, we stick to the current solution, to move foreward.

**Comment by rathrio** [comment]
@simplay for bravery! :+1:

**Pull request merged**
