### PR TITLE
Introduced simple reddit crawler

### PR DESCRIPTION
**Pull request by simplay**
WIP
- crawl content from 'new' and arbitrary subreddits
- support crawling images from r/pics

### CODE REVIEW

**Comment by simplay** [comment]
@rathrio: any opinions/suggestions?

**Comment by simplay** [comment]
@rathrio: is there any way to speed up the crawling procedure? atm it takes about 2-3s to fetch, parse and report reddit content (which is rather slow).

**Comment by rathrio** [comment]
@simplay Will check this out today

**Comment by simplay** [comment]
@rathrio: I'm gonna merge this PR even though the crawler is still still as fuck. An improvement will follow in a later PR.

**Comment by rathrio** [comment]
@simplay that's fine

**Comment by rathrio** [comment]
:+1:

**Pull request merged**
